const API = window.APP_CONFIG?.API_URL || '';
let properties = [], adminProperties = [], sessionToken = sessionStorage.getItem('adminToken') || '';
let photoItems = []; // {kind:'existing'|'new', url?, file?, preview, key}
const $ = s => document.querySelector(s);
const esc = (v='') => String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money = (n,c='MXN') => new Intl.NumberFormat('es-MX',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(n)||0);
const cleanPhone = v => String(v||'').replace(/\D/g,'');

if(window.APP_CONFIG?.BRAND_NAME){ document.title=`${window.APP_CONFIG.BRAND_NAME} | Propiedades`; }
async function api(action,payload={}){if(!API||API.includes('PEGA_AQUI'))throw new Error('Configura API_URL en config.js');const r=await fetch(API,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action,...payload})});const d=await r.json();if(!d.ok)throw new Error(d.error||'Error en el servidor');return d;}

async function loadProperties(){try{const d=await api('listPublic');properties=d.properties||[];renderProperties()}catch(e){$('#propertyGrid').innerHTML=`<p>${esc(e.message)}</p>`}}
function renderProperties(){
  const q=$('#search').value.toLowerCase(),type=$('#typeFilter').value,op=$('#operationFilter').value;
  const f=properties.filter(p=>(!type||p.type===type)&&(!op||p.operation===op)&&`${p.title} ${p.location} ${p.type} ${p.features?.join(' ')}`.toLowerCase().includes(q));
  $('#propertyGrid').innerHTML=f.map(p=>`<article class="property-card" data-id="${esc(p.id)}"><div class="card-image"><img loading="lazy" src="${esc((p.photos||[])[0]||'https://placehold.co/1200x800?text=Propiedad')}" alt="${esc(p.title)}"><span class="badge">${esc(p.operation==='renta'?'Renta':'Venta')}</span></div><div class="card-body"><p class="eyebrow">${esc(p.type||'Propiedad')}</p><h3>${esc(p.title)}</h3><p class="meta">${esc(p.location||'Ubicación por confirmar')}</p><div class="card-stats"><span>${Number(p.bedrooms)||0} rec.</span><span>${Number(p.bathrooms)||0} baños</span><span>${Number(p.construction)||0} m²</span></div><p class="price">${money(p.price,p.currency)}${p.operation==='renta'?'<small>/mes</small>':''}</p></div></article>`).join('');
  $('#emptyState').hidden=f.length>0;
  [...new Set(properties.map(p=>p.type).filter(Boolean))].sort().forEach(t=>{if(![...$('#typeFilter').options].some(o=>o.value===t))$('#typeFilter').add(new Option(t,t))});
}

function setDetailMainImage(container,src){
  const img=container.querySelector('[data-detail-main-image]');
  if(img) img.src=src;
  container.querySelectorAll('[data-detail-thumb]').forEach(btn=>btn.classList.toggle('active',btn.dataset.url===src));
}

function openProperty(id){
  const p=properties.find(x=>String(x.id)===String(id));
  if(!p)return;
  const photos=(p.photos||[]).filter(Boolean),phone=cleanPhone(p.sellerPhone),mainImage=photos[0]||'https://placehold.co/1400x900?text=Propiedad';
  const collage=photos.slice(1,5),thumbs=photos.length?photos:[mainImage];
  const detail=$('#propertyDetail');
  detail.innerHTML=`<div class="detail-shell"><div class="detail-media-card"><div class="detail-hero-grid"><div class="detail-main-stage"><img data-detail-main-image src="${esc(mainImage)}" alt="${esc(p.title)}"></div><div class="detail-collage">${collage.length?collage.map((u,i)=>`<button type="button" class="detail-thumb ${i===0?'active':''}" data-detail-thumb data-url="${esc(u)}"><img loading="lazy" src="${esc(u)}" alt="Vista ${i+2} de ${esc(p.title)}"></button>`).join(''):'<div class="detail-collage-placeholder">Galería profesional<br>de la propiedad</div>'}</div></div><div class="detail-thumbnail-rail">${thumbs.map((u,i)=>`<button type="button" class="detail-thumb ${u===mainImage?'active':''}" data-detail-thumb data-url="${esc(u)}"><img loading="lazy" src="${esc(u)}" alt="Miniatura ${i+1} de ${esc(p.title)}"></button>`).join('')}</div></div><aside class="detail-side-card"><p class="eyebrow">${esc(p.type||'Propiedad')} · ${esc(p.operation==='renta'?'Renta':'Venta')}</p><h2>${esc(p.title)}</h2><p class="detail-location">${esc(p.location||'Ubicación por confirmar')}</p><p class="price">${money(p.price,p.currency)}${p.operation==='renta'?'<small>/mes</small>':''}</p><div class="detail-stats-grid"><div class="detail-stat"><strong>${Number(p.bedrooms)||0}</strong><span>Recámaras</span></div><div class="detail-stat"><strong>${Number(p.bathrooms)||0}</strong><span>Baños</span></div><div class="detail-stat"><strong>${Number(p.construction)||0}</strong><span>m² constr.</span></div><div class="detail-stat"><strong>${Number(p.land)||0}</strong><span>m² terreno</span></div></div><div class="detail-contact-box"><h3>Contacto</h3><p>${esc(p.sellerName||'Asesora MARZA')}</p>${p.sellerPhone?`<p>${esc(p.sellerPhone)}</p>`:''}${p.sellerEmail?`<p>${esc(p.sellerEmail)}</p>`:''}</div><div class="detail-actions"><button class="primary" onclick="downloadPdf('${esc(p.id)}')">Descargar PDF</button>${phone?`<a class="secondary" target="_blank" rel="noopener" href="https://wa.me/${phone}?text=${encodeURIComponent('Hola, me interesa la propiedad: '+p.title)}">Hablar por WhatsApp</a>`:''}<button class="secondary" onclick="startAppointment('${esc(p.id)}')">Agendar visita</button></div></aside><section class="detail-info-card"><div class="detail-info-grid"><div><h3>Descripción</h3><p class="description">${esc(p.description||'Próximamente agregaremos la descripción completa de esta propiedad.')}</p></div><div><h3>Características destacadas</h3>${p.features?.length?`<ul class="features modern">${p.features.map(f=>`<li>${esc(f)}</li>`).join('')}</ul>`:'<p class="description">La asesora podrá agregar amenidades, ventajas y detalles diferenciales de esta propiedad.</p>'}</div></div></section></div>`;
  detail.querySelectorAll('[data-detail-thumb]').forEach(btn=>btn.addEventListener('click',()=>setDetailMainImage(detail,btn.dataset.url)));
  $('#propertyDialog').showModal();
}

function openExternal(url){
  const a=document.createElement('a');
  a.href=url;
  a.target='_blank';
  a.rel='noopener';
  document.body.appendChild(a);
  a.click();
  a.remove();
}

async function downloadPdf(id){
  try{
    const prop=properties.find(x=>String(x.id)===String(id));
    if(prop?.pdfUrl){ openExternal(prop.pdfUrl); return; }
    const d=await api('getPdf',{id});
    const url=d.downloadUrl||d.viewUrl||d.url;
    if(!url) throw new Error('No fue posible obtener el PDF.');
    if(prop) prop.pdfUrl=d.viewUrl||d.url||url;
    openExternal(url);
  }catch(e){alert(e.message)}
}
function startAppointment(id){const p=properties.find(x=>String(x.id)===String(id));$('#propertyDialog').close();openChat();bot(`Claro. Te ayudo a solicitar una visita para “${p?.title||'esta propiedad'}”. ¿Qué día y horario prefieres?`);window.chatContext={propertyId:id,step:'date'}}

$('#search').addEventListener('input',renderProperties);$('#typeFilter').addEventListener('change',renderProperties);$('#operationFilter').addEventListener('change',renderProperties);$('#propertyGrid').addEventListener('click',e=>{const c=e.target.closest('.property-card');if(c)openProperty(c.dataset.id)});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
$('#adminOpen').onclick=async()=>{sessionToken?await showAdmin():showLogin();$('#adminDialog').showModal()};function showLogin(){$('#loginPanel').hidden=false;$('#adminPanel').hidden=true}async function showAdmin(){$('#loginPanel').hidden=true;$('#adminPanel').hidden=false;await loadAdminProperties()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const d=await api('login',{password:$('#adminPassword').value});sessionToken=d.token;sessionStorage.setItem('adminToken',sessionToken);$('#loginMessage').textContent='';await showAdmin()}catch(err){$('#loginMessage').textContent=err.message}};$('#logout').onclick=()=>{sessionToken='';sessionStorage.removeItem('adminToken');showLogin()};

async function loadAdminProperties(){try{const d=await api('listAdmin',{token:sessionToken});adminProperties=d.properties||[];renderAdminList()}catch(e){if(/Sesión/.test(e.message)){sessionToken='';sessionStorage.removeItem('adminToken');showLogin()}else $('#saveMessage').textContent=e.message}}
function renderAdminList(){const q=$('#adminSearch').value.toLowerCase();const list=adminProperties.filter(p=>`${p.title} ${p.location} ${p.status}`.toLowerCase().includes(q));$('#adminPropertyList').innerHTML=list.map(p=>`<button type="button" class="inventory-item ${String(p.id)===String($('#propertyId').value)?'active':''}" data-id="${esc(p.id)}"><img src="${esc((p.photos||[])[0]||'https://placehold.co/120?text=Sin+foto')}" alt=""><span><strong>${esc(p.title)}</strong><small>${esc(p.location)}</small><em class="status-${esc(p.status)}">${esc(p.status)}</em></span></button>`).join('')||'<p class="empty-small">Sin propiedades.</p>'}
$('#adminSearch').oninput=renderAdminList;$('#adminPropertyList').onclick=e=>{const b=e.target.closest('[data-id]');if(b)editProperty(b.dataset.id)};$('#newProperty').onclick=resetForm;
function editProperty(id){const p=adminProperties.find(x=>String(x.id)===String(id));if(!p)return;resetForm();$('#formHeading').textContent='Editar propiedad';$('#propertyId').value=p.id;['title','type','operation','price','currency','location','bedrooms','bathrooms','construction','land','description','sellerName','sellerPhone','sellerEmail','status'].forEach(k=>{const el=$('#'+k);if(el)el.value=p[k]??''});$('#features').value=(p.features||[]).join('\n');photoItems=(p.photos||[]).map((url,i)=>({kind:'existing',url,preview:url,key:`existing-${i}-${url}`}));renderPhotoPreview();$('#deleteProperty').hidden=false;renderAdminList()}
function resetForm(){$('#propertyForm').reset();$('#propertyId').value='';$('#operation').value='venta';$('#currency').value='MXN';$('#status').value='publicada';$('#formHeading').textContent='Nueva propiedad';$('#deleteProperty').hidden=true;$('#saveMessage').textContent='';photoItems=[];renderPhotoPreview();renderAdminList()}

async function compressImage(file,maxWidth=1800,quality=.82){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const scale=Math.min(1,maxWidth/img.width),canvas=document.createElement('canvas');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{URL.revokeObjectURL(url);if(!blob)return reject(new Error('No se pudo procesar una imagen.'));resolve(new File([blob],file.name.replace(/\.[^.]+$/,'.jpg'),{type:'image/jpeg'}))},'image/jpeg',quality)};img.onerror=()=>reject(new Error(`No se pudo leer ${file.name}`));img.src=url})}
$('#photos').onchange=async e=>{const files=[...e.target.files];$('#saveMessage').textContent='Optimizando fotografías…';try{for(const original of files){const file=await compressImage(original);photoItems.push({kind:'new',file,preview:URL.createObjectURL(file),key:`new-${crypto.randomUUID()}`})}renderPhotoPreview();$('#saveMessage').textContent=`${files.length} fotografía(s) agregada(s).`}catch(err){$('#saveMessage').textContent=err.message}e.target.value=''};
function renderPhotoPreview(){$('#photoPreview').innerHTML=photoItems.map((x,i)=>`<figure draggable="true" data-key="${esc(x.key)}"><img src="${esc(x.preview)}" alt="Foto ${i+1}"><figcaption>${i===0?'★ Portada':`Foto ${i+1}`}</figcaption><button type="button" class="remove-photo" data-remove="${esc(x.key)}" aria-label="Eliminar fotografía">×</button><span class="drag-handle">⠿</span></figure>`).join('')}
let draggedKey='';$('#photoPreview').addEventListener('dragstart',e=>{const f=e.target.closest('figure');if(f){draggedKey=f.dataset.key;e.dataTransfer.effectAllowed='move'}});$('#photoPreview').addEventListener('dragover',e=>e.preventDefault());$('#photoPreview').addEventListener('drop',e=>{e.preventDefault();const target=e.target.closest('figure');if(!target||target.dataset.key===draggedKey)return;const from=photoItems.findIndex(x=>x.key===draggedKey),to=photoItems.findIndex(x=>x.key===target.dataset.key);const [item]=photoItems.splice(from,1);photoItems.splice(to,0,item);renderPhotoPreview()});$('#photoPreview').addEventListener('click',e=>{const key=e.target.dataset.remove;if(!key)return;const item=photoItems.find(x=>x.key===key);if(item?.kind==='new')URL.revokeObjectURL(item.preview);photoItems=photoItems.filter(x=>x.key!==key);renderPhotoPreview()});
const toBase64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve({clientKey:file.__clientKey,name:file.name,type:file.type,data:String(r.result).split(',')[1]});r.onerror=reject;r.readAsDataURL(file)});
$('#propertyForm').onsubmit=async e=>{e.preventDefault();$('#saveMessage').textContent='Guardando…';try{const newItems=photoItems.filter(x=>x.kind==='new');const files=[];for(const item of newItems){item.file.__clientKey=item.key;files.push(await toBase64(item.file))}const photoOrder=photoItems.map(x=>x.kind==='existing'?{kind:'existing',url:x.url}:{kind:'new',clientKey:x.key});const property={id:$('#propertyId').value,title:$('#title').value,type:$('#type').value,operation:$('#operation').value,price:$('#price').value,currency:$('#currency').value,location:$('#location').value,bedrooms:$('#bedrooms').value,bathrooms:$('#bathrooms').value,construction:$('#construction').value,land:$('#land').value,description:$('#description').value,features:$('#features').value.split('\n').map(x=>x.trim()).filter(Boolean),sellerName:$('#sellerName').value,sellerPhone:$('#sellerPhone').value,sellerEmail:$('#sellerEmail').value,status:$('#status').value};const d=await api('saveProperty',{token:sessionToken,property,files,photoOrder});$('#saveMessage').textContent='Propiedad guardada correctamente.';await Promise.all([loadProperties(),loadAdminProperties()]);editProperty(d.id)}catch(err){$('#saveMessage').textContent=err.message}};
$('#deleteProperty').onclick=async()=>{const id=$('#propertyId').value;if(!id||!confirm('¿Eliminar esta propiedad y sus fotografías? Esta acción no se puede deshacer.'))return;try{await api('deleteProperty',{token:sessionToken,id});resetForm();await Promise.all([loadProperties(),loadAdminProperties()])}catch(e){$('#saveMessage').textContent=e.message}};

function openChat(){$('#chatPanel').hidden=false;if(!$('#chatMessages').children.length)bot('Hola. Puedo ayudarte a buscar por zona, presupuesto, tipo de inmueble o recámaras; también puedo solicitar una visita.')}function bot(t){$('#chatMessages').insertAdjacentHTML('beforeend',`<div class="bubble">${esc(t)}</div>`);$('#chatMessages').scrollTop=99999}function user(t){$('#chatMessages').insertAdjacentHTML('beforeend',`<div class="bubble user">${esc(t)}</div>`)}$('#chatButton').onclick=openChat;document.querySelectorAll('[data-open-chat]').forEach(button=>button.addEventListener('click',openChat));$('#chatClose').onclick=()=>$('#chatPanel').hidden=true;
$('#chatForm').onsubmit=async e=>{e.preventDefault();const text=$('#chatInput').value.trim();if(!text)return;user(text);$('#chatInput').value='';const ctx=window.chatContext||{};if(ctx.step==='date'){ctx.date=text;ctx.step='name';bot('¿A nombre de quién registro la solicitud?')}else if(ctx.step==='name'){ctx.name=text;ctx.step='contact';bot('Compárteme tu teléfono o correo para que la asesora confirme la cita.')}else if(ctx.step==='contact'){ctx.contact=text;try{await api('requestAppointment',{appointment:ctx});bot('Solicitud enviada. La asesora se comunicará contigo para confirmar fecha y hora.');window.chatContext={}}catch(err){bot('No pude registrar la cita: '+err.message)}}else if(/cita|visita|agendar/i.test(text)){bot('Abre la propiedad que te interesa y pulsa “Agendar visita”.')}else if(/asesor|vendedor|whatsapp|hablar/i.test(text)){const p=properties.find(x=>x.sellerPhone);bot(p?`Puedes contactar a ${p.sellerName||'la asesora'} al WhatsApp ${p.sellerPhone}.`:'Todavía no hay un teléfono configurado.')}else{const amount=(text.match(/(?:\$|mxn|pesos?)\s?([\d,.]+)/i)||text.match(/([\d,.]+)\s?(?:mil|millones?)/i));let hits=properties.filter(p=>`${p.title} ${p.location} ${p.type} ${p.operation} ${(p.features||[]).join(' ')}`.toLowerCase().includes(text.toLowerCase()));if(!hits.length){const words=text.toLowerCase().split(/\s+/).filter(w=>w.length>3);hits=properties.map(p=>({p,score:words.filter(w=>`${p.title} ${p.location} ${p.type} ${(p.features||[]).join(' ')}`.toLowerCase().includes(w)).length})).filter(x=>x.score).sort((a,b)=>b.score-a.score).map(x=>x.p)}bot(hits.length?`Encontré ${hits.slice(0,3).map(x=>`${x.title} (${money(x.price,x.currency)})`).join(', ')}. Puedes verlas en el catálogo.`:'No encontré una coincidencia exacta. Prueba con una zona, “casa”, “departamento”, “renta” o número de recámaras.') }};
resetForm();loadProperties();
